// import { Geist, Geist_Mono } from "next/font/google";
import { GeistSans } from 'geist/font/sans';
import { GeistMono } from 'geist/font/mono';
import "./globals.css";
import NavBar from './components/NavBar';
import { NextAuthProvider } from "./provider";
import { getAutenticatedhUser } from "@/lib/getAuthUser";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const authUser=await getAutenticatedhUser();
  return (
    <html lang="en"
    className={`${GeistSans.variable} ${GeistMono.variable} scroll-smooth`}
    >
      <body>
        <NextAuthProvider>
        <div className="maxt-w-full mx-auto text-white">
        <NavBar authUser={authUser}/>
        <div className="min-h-screen h-full w-full bg-linear-45 from-[#12243c] to-[#0f1222]">
        {children}
        </div>
      </div>
      </NextAuthProvider>
      </body>
    </html>
  );
}
